import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "./navigation";

export const BaseNeue = localFont({
  src: './font/BaseNeueTrial-CondSemBdObliq.woff2'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <head>
        <title>Title</title>
        <meta name='description' content='Description' />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${BaseNeue.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
