import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "./navigation";

export const BaseNeue = localFont({
  src: './font/BaseNeueTrial-CondSemBdObliq.woff2'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <head>
        <title>Title</title>
        <meta name='description' content='Description' />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${BaseNeue.className} antialiased bg-black text-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}

import "./globals.css";

// 1. Viewport settings (must be separate from metadata in Next.js 14+)
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Prevents zooming on mobile
  themeColor: "#000000",
};

// 2. Metadata settings (SEO & PWA)
export const metadata = {
  title: "3D Lens Effect",
  description: "Interactive 3D Glass Distortion",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "3D Lens",
  },
};

// 3. The Layout Component (Only ONE default export allowed)
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="antialiased bg-black text-white">
//         {children}
//       </body>
//     </html>
//   );
// }


